#
#person:
#  name: zhangsan
#  age: 16
#  isBoss: false
#  maps: {k1: v1,k2: v2}
#  list:
#    - ls1
#    - ls2
#  dog:
#    nickname: poppy
#    petId: 2
#spring:
#  datasource:
#    username: dzzmdbid
#    password: psw@501098
#    url: jdbc:oracle:thin:@localhost:1521/orclpdb1
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    schema:
#      -classpath: sql/schema-all.sql
