
CREATE TABLE CUSTOMERS_LIST
(
    ID                NUMBER,
    NAME              VARCHAR2(30) NOT NULL ,
    GENDER            VARCHAR2(2),
    BIRTHDAY          DATE,
    EMAIL             VARCHAR2(30) NOT NULL ,
    CONTACT_NUMBER    VARCHAR2(13) NOT NULL ,
    CITY              VARCHAR2(10),
    DISTRICT          VARCHAR2(30),
    ZIP_CODE          NUMBER,
    START_DATE        DATE,
    END_DATE          DATE,
    LAST_UPDATED_DATE TIMESTAMP DEFAULT CURRENT_DATE,
    LAST_UPDATED_BY   VARCHAR2(20),
    CONSTRAINT CUSTOMER_PK PRIMARY KEY (NAME, CONTACT_NUMBER)
);


CREATE TABLE DEPARTMENT_LIST
(
    ZIP_CODE NUMBER,
    DISTRICT VARCHAR2(20),
    ADDRESS  VARCHAR2(100),
    CITY     VARCHAR2(20)
);
